posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    text = TextAreaField('Text')

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag

from flask import request

from .forms import PostForm
from app import db

from flask import redirect, url_for

from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        text = request.form['text']

        try:
            post = Post(title=title, text=text)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wrong')

        return redirect( url_for('posts.index') )

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/')
def index():
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.text.contains(q))
    else:
        posts = Post.query.order_by(Post.created_at.desc())

    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tag = post.tags
    return render_template('posts/post_detail.html', post=post, tag=tag)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def post_edit(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
Publish new post

{% endblock %}

{% block content_title %}
New post

{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post')}}" method="POST">
        {% for f in form %}
        <div class="form-group">
            {{ f.label(class='control-label') }}
            {{ f(class='form-control') }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Create</button>
    </form>
    </div>


{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}
Edit post

{% endblock %}

{% block content_title %}
Edit post

{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.post_edit', slug=post.slug)}}" method="POST">
        {% for f in form %}
        <div class="form-group">
            {{ f.label(class='control-label') }}
            {{ f(class='form-control') }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Edit</button>
    </form>
    </div>


{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Posts

{% endblock %}

{% block content_title %}
Published posts

{% endblock %}

{% block content %}

<div class="col-md-6">
    <form action="{{ url_for('posts.create_post')}}" method="GET">
<button type="submit" class="btn btn-lg btn-primary">Create post</button>
    </form>
</div>

    {% for post in pages.items %}
<ul><li>
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{post.title}} {{post.created_at}} </a>
</li></ul>
{% endfor %}


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

    <li
            {% if not pages.has_prev %}
            class="page-item disabled"
        {% endif %}
    >
      <a href="./?page={{ pages.prev_num}}" class="page-link">Previous</a>
    </li>
      {% for page in pages.iter_pages() %}
          <li {% if page == pages.page %} class="page-item" {% endif %}><a class="page-link" href="./?page={{ page}}"
          >{{ page}}</a></li>
      {% endfor %}


    <li {% if not pages.has_next %}
            class="page-item"
    {% endif %} >
      <a class="page-link" href="./?page={{ pages.next_num}}">Next</a>
    </li>
  </ul>
</nav>


{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}

{% endblock %}

{% block content_title %}
{{ post.title }}

{% endblock %}

{% block content %}

<div class="col-md-6">
    <form action="{{ url_for('posts.post_edit', slug=post.slug)}}" method="GET">
<button type="submit" class="btn btn-lg btn-primary">Edit post</button>
    </form>
</div>


<div class="tags">
    {% for t in tag %}<a href="{{ url_for('posts.tag_detail', slug=t.slug) }}">
    <span class="badge bg-info text-dark">{{t.title}}</span></a>
    {% endfor %}
</div>
<div class="content">
    {{ post.text }}
    </div>

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
{{ tag.title }}

{% endblock %}

{% block content_title %}
{{ tag.title }}

{% endblock %}

{% block content %}
    {% for post in posts %}
<div class="post">
<a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{post.title}} {{post.created_at}} </a>
    </div>
    {% endfor %}


{% endblock %}